default_config:
logger:
  default: error
  logs:
    custom_components.open_route_service: debug



sensor:
  - platform: open_route_service
    api_key: !secret api_key
    origin_latitude: "49.41461"
    origin_longitude: "8.681495"
    destination_latitude: "49.420318"
    destination_longitude: "8.687872"