name: HACS validation

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/integration/action@master"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CATEGORY: "integration"
        env:
          SKIP_BRANDS_CHECK: "True"
