name: Hassfest

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
