name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v2
          - name: Use Node.js 12.x
            uses: actions/setup-node@v2.1.2
            with:
                node-version: 12.x
          - name: Install semantic release
            run: npm install semantic-release
          - name: Create new release
            uses: cycjimmy/semantic-release-action@v2
            id: semantic
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}